### ISSUE TITLE
Unable to create notification-configurations

### ISSUE THREAD

**Issue by atugade** [adeo/iwc-tfc-client#7]
**Describe the bug**
I am unable to create a notification configuration from that sample in the README

**To Reproduce**
Try creating a notification with:

```
# Create a Notification configuration
my_notification = new_ws.create(
    "notification-configuration",
    enabled=True,
    name="MyNotif",
    url="https://httpstat.us/200",
    destination_type=NotificationsDestinationType.generic,
    token="TestToken",
    triggers=[NotificationTrigger.created],
)
```

**Expected behavior**
Creates a notification config

**Screenshots or similare**
```
Traceback (most recent call last):
  File "tf_create_workspace_tfcclient.py", line 21, in <module>
    ws.create(
  File "/Users/arwintugade/work/okta/lib/python3.8/site-packages/tfc_client/tfc_objects.py", line 339, in create
    return super().create(object_type, url_prefix=url_prefix, **kwargs)
  File "/Users/arwintugade/work/okta/lib/python3.8/site-packages/tfc_client/tfc_objects.py", line 110, in create
    api_response = self.client._api.post(path=path, data=payload.json())
  File "/Users/arwintugade/work/okta/lib/python3.8/site-packages/tfc_client/api_caller.py", line 140, in post
    return self._call(method="post", **kwargs)
  File "/Users/arwintugade/work/okta/lib/python3.8/site-packages/tfc_client/api_caller.py", line 67, in _call
    raise APIException(f"APIError code: {response.status_code}", response)
tfc_client.exception.APIException: ('APIError code: 404', <Response [404]>)
```

**Desktop (please complete the following information):**
 - OS: OSX
 - Version: 10.15.6
 - Python version 3.8.5
 - `pip freeze` of your environment

```
astroid==2.4.2
awscli==1.18.115
beautifulsoup4==4.9.1
boto3==1.14.38
botocore==1.17.38
certifi==2020.6.20
cffi==1.14.1
chardet==3.0.4
click==7.1.2
colorama==0.4.3
configparser==3.8.1
cryptography==3.0
dnspython==2.0.0
docutils==0.15.2
email-validator==1.1.1
fido2==0.8.1
gimme-aws-creds==2.3.4
idna==2.10
inflection==0.5.1
isort==5.5.3
jmespath==0.10.0
keyring==21.3.0
lazy-object-proxy==1.4.3
mccabe==0.6.1
okta==0.0.4
pep8==1.7.1
pyasn1==0.4.8
pycodestyle==2.6.0
pycparser==2.20
pydantic==1.6.1
pylint==2.6.0
pyterprise==0.0.15
python-dateutil==2.8.0
PyYAML==5.3.1
requests==2.24.0
rsa==4.5
s3transfer==0.3.3
six==1.15.0
soupsieve==2.0.1
tfc-client==0.7.2
toml==0.10.1
urllib3==1.25.10
wrapt==1.12.1
```

**Comment by alex-ikse** [comment]
Thank you for your report, but the problem is not with tfc-clieent lib, but with the service used in the example (httpstat.us).

This service (that simulate a http code for webhook debug/dev purpose) is down right now (They are under attack).

See: https://github.com/Readify/httpstatus/issues/89

Please test again with a "real" webhook URL.
